### PR TITLE
Cryptic News

### PR DESCRIPTION
**Pull request by mediocregopher**
Screenshot 2022-01-09 16 02 35

------

This commit changes the site to be a link aggregator, rather than a
syndicator. All blog posts are now only linked to, and more blogs have
been added. Changes required for this include:

* Rename `Blog` -> `News` in all places.

* Upgrading `syndicate-rss` dependency so we can use no command-line
  arguments. The new version cleans the filenames of the content files
  differently, so a lot of the file names inside `content` changed
  because of this.

* Inclusion of cryptic logo SVG. This is a fixed version of the previous
  one which was floating around, as that one didn't render properly on
  chrome. This new SVG is displayed in the title, and used as the
  favicon.

* Upgrading `nixpkgs` so we can get the latest zola, because the
  previous one didn't properly set the `Content-Type` of the SVG in dev
  mode, and so the SVG didn't display correctly in dev.

------

I'm open to feedback on all of it. I'm sure my html/css is not "the right way", but it seems to work on mobile sizes well enough. Also we don't have to add all the blogs I added here, these are ones I've come across that I've liked the general feel of, but some are kinda spammy too (Seth seems to have a-post-a-day lined up since the new year). I feel like if we add enough feeds added in the future the once-a-day blogs won't stand out as much.

### CODE REVIEW

**Comment by mediocregopher** [comment]
Other blogs that might be worth adding:

https://blog.jim-nielsen.com/
https://vitalik.ca/index.html
https://solar.lowtechmagazine.com/

**Comment by MarcoPolo** [comment]
Can you split the real changes and the changes that are just the deletions? It's hard to navigate this otherwise.

**Comment by MarcoPolo** [comment]
Ah actually I can filter out the markdown files. That's good enough.

**Review by MarcoPolo — APPROVED** [review]
looks good!

**Comment by mediocregopher** [comment]
Thanks! Just a note for myself more than anything, here's another blog that I like the vibe of: https://unixsheikh.com/index.html

**Pull request merged**
